os:
  - linux
  - osx

language: cpp

dist: trusty

addons:
  apt:
    packages:
      - gcc-7
      - g++-7
      - libqt-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install qt5 cmake ;
      brew link --force qt ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7 ;
      export CXX=g++-7 ;
